const products = [
  {
    id: "infinix-hot-12i",
    name: "Infinix HOT 12i",
    price: 4295,
    brand: "Infinix",
    memory: "64",
    image: "https://i.postimg.cc/VkTJVnX3/Infinix-HOT-12i.png",
    camera: "13MP",
    megapixels: "13",
    cameraCount: "2",
    description:
      "Мощный смартфон с большим экраном и долгим временем работы от батареи, идеально подходящий для повседневных задач и развлечений.",
  },
  {
    id: "infinix-hot-12-play",
    name: "Infinix HOT 12 Play",
    price: 4495,
    brand: "Infinix",
    memory: "64",
    image: "https://i.postimg.cc/WbYzdgYh/Infinix-HOT-12-Play.png",
    camera: "13MP",
    megapixels: "13",
    cameraCount: "2",
    description:
      "Оптимизированный для игр и развлечений, этот смартфон предлагает плавную работу и долгое время автономной работы.",
  },
  {
    id: "honor-x9c",
    name: "Honor X9c",
    price: 35890,
    brand: "Honor",
    memory: "256",
    image: "https://i.postimg.cc/bJPN7TrF/Honor-X9c.png",
    camera: "108MP",
    megapixels: "108",
    cameraCount: "3",
    description:
      "Флагманская камера, большой объем памяти и стильный дизайн делают этот смартфон идеальным для профессиональной фотографии и хранения данных.",
  },
  {
    id: "honor-x8c",
    name: "Honor X8c",
    price: 24990,
    brand: "Honor",
    memory: "128",
    image: "https://i.postimg.cc/zGWNqgsm/Honor-X8c.png",
    camera: "48MP",
    megapixels: "48",
    cameraCount: "4",
    description:
      "Современный смартфон с мощной квадро-камерой, обеспечивающей высокое качество снимков, и быстрой производительностью.",
  },
  {
    id: "honor-x7c",
    name: "Honor X7c",
    price: 17590,
    brand: "Honor",
    memory: "128",
    image: "https://i.postimg.cc/523VHV2p/Honor-X7c.png",
    camera: "50MP",
    megapixels: "50",
    cameraCount: "3",
    description:
      "Элегантный смартфон с тройной камерой, большим экраном и емким аккумулятором для ежедневного использования без компромиссов.",
  },
  {
    id: "honor-x6b",
    name: "Honor X6b",
    price: 12890,
    brand: "Honor",
    memory: "64",
    image: "https://i.postimg.cc/1z3ZwjgS/Honor-X6b.png",
    camera: "50MP",
    megapixels: "50",
    cameraCount: "2",
    description:
      "Бюджетный, но функциональный смартфон с хорошей камерой и достаточным объемом памяти для всех основных приложений.",
  },
  {
    id: "xiaomi-redmi-note-14-pro",
    name: "Xiaomi Redmi Note 14 Pro",
    price: 23990,
    brand: "Xiaomi",
    memory: "128",
    image: "https://i.postimg.cc/GmzWLxX5/Xiaomi-Redmi-Note-14-Pro.png",
    camera: "200MP",
    megapixels: "200",
    cameraCount: "3",
    description:
      "Флагманский смартфон с невероятной камерой на 200MP, предназначенный для создания профессиональных фотографий и видео.",
  },
  {
    id: "xiaomi-redmi-note-14",
    name: "Xiaomi Redmi Note 14",
    price: 17990,
    brand: "Xiaomi",
    memory: "64",
    image: "https://i.postimg.cc/Nj0N4qxd/Xiaomi-Redmi-Note-14.png",
    camera: "108MP",
    megapixels: "108",
    cameraCount: "3",
    description:
      "Мощный и доступный смартфон с камерой высокого разрешения и продолжительным временем работы от батареи.",
  },
  {
    id: "xiaomi-14t",
    name: "Xiaomi 14T",
    price: 48990,
    brand: "Xiaomi",
    memory: "256",
    image: "https://i.postimg.cc/vmBpcxjH/Xiaomi-14-T.png",
    camera: "50MP",
    megapixels: "50",
    cameraCount: "3",
    description:
      "Ультрасовременный смартфон с топовыми характеристиками, быстрой зарядкой и передовой системой камер для самых требовательных пользователей.",
  },
  {
    id: "infinix-smart-9",
    name: "Infinix Smart 9",
    price: 8990,
    brand: "Infinix",
    memory: "64",
    image: "https://i.postimg.cc/rsSHv1dg/Infinix-Smart-9.png",
    camera: "13MP",
    megapixels: "13",
    cameraCount: "2",
    description:
      "Надежный и простой в использовании смартфон с базовым набором функций для связи и интернета.",
  },
  {
    id: "xiaomi-redmi-14c",
    name: "Xiaomi Redmi 14C",
    price: 9499,
    brand: "Xiaomi",
    memory: "128",
    image: "https://i.postimg.cc/2yVXgr7j/Xiaomi-Redmi-14-C.png",
    camera: "50MP",
    megapixels: "50",
    cameraCount: "2",
    description:
      "Отличный бюджетный выбор с большим объемом памяти и качественной камерой, идеально подходящий для молодежи.",
  },
  {
    id: "xiaomi-redmi-a5",
    name: "Xiaomi Redmi A5",
    price: 7799,
    brand: "Xiaomi",
    memory: "64",
    image: "https://i.postimg.cc/k4D0PQnd/Xiaomi-Redmi-A5.png",
    camera: "13MP",
    megapixels: "13",
    cameraCount: "2",
    description:
      "Супербюджетный смартфон для тех, кому нужны только звонки, мессенджеры и базовые приложения.",
  },

  {
    id: "apple-iphone-14-pro",
    name: "Apple iPhone 14 Pro",
    price: 109990,
    brand: "Apple",
    memory: 256,
    image: "https://i.postimg.cc/1tSqsS9R/Apple-i-Phone-14-Pro.png",
    camera: "48MP",
    megapixels: 48,
    cameraCount: 3,
    description:
      "Профессиональная производительность и инновационная система камер для создания контента.",
  },
  {
    id: "apple-iphone-14",
    name: "Apple iPhone 14",
    price: 89990,
    brand: "Apple",
    memory: 128,
    image: "https://i.postimg.cc/pdzFwrM1/Apple-i-Phone-14.png",
    camera: "12MP",
    megapixels: 12,
    cameraCount: 2,
    description:
      "Высокая производительность и надёжность для повседневного использования.",
  },
  {
    id: "apple-iphone-se",
    name: "Apple iPhone SE",
    price: 49990,
    brand: "Apple",
    memory: 64,
    image: "https://i.postimg.cc/7hsG3TSb/Apple-i-Phone-SE.png",
    camera: "12MP",
    megapixels: 12,
    cameraCount: 1,
    description: "Классический дизайн и мощный процессор в компактном корпусе.",
  },
  {
    id: "apple-iphone-13-mini",
    name: "Apple iPhone 13 mini",
    price: 79990,
    brand: "Apple",
    memory: 128,
    image: "https://i.postimg.cc/Vk3tZMpC/Apple-i-Phone-13-mini.png",
    camera: "12MP",
    megapixels: 12,
    cameraCount: 2,
    description:
      "Компактный смартфон с отличной камерой и длительным временем работы от батареи.",
  },
  {
    id: "samsung-galaxy-s23-ultra",
    name: "Samsung Galaxy S23 Ultra",
    price: 99990,
    brand: "Samsung",
    memory: 512,
    image: "https://i.postimg.cc/pX3yPvCN/Samsung-Galaxy-S23-Ultra.png",
    camera: "200MP",
    megapixels: 200,
    cameraCount: 4,
    description:
      "Флагманский смартфон с мощнейшей камерой и стилусом S Pen для максимальной продуктивности.",
  },
  {
    id: "samsung-galaxy-a54",
    name: "Samsung Galaxy A54",
    price: 35000,
    brand: "Samsung",
    memory: 128,
    image: "https://i.postimg.cc/9FDr30Gt/Samsung-Galaxy-A54.png",
    camera: "50MP",
    megapixels: 50,
    cameraCount: 3,
    description:
      "Надёжный смартфон среднего класса с ярким экраном и хорошей камерой.",
  },
  {
    id: "samsung-galaxy-z-fold4",
    name: "Samsung Galaxy Z Fold4",
    price: 150000,
    brand: "Samsung",
    memory: 256,
    image: "https://i.postimg.cc/s2rXZJbw/Samsung-Galaxy-Z-Fold4.png",
    camera: "50MP",
    megapixels: 50,
    cameraCount: 3,
    description:
      "Инновационный складной смартфон, объединяющий возможности планшета и телефона.",
  },
  {
    id: "samsung-galaxy-a13",
    name: "Samsung Galaxy A13",
    price: 14000,
    brand: "Samsung",
    memory: 64,
    image: "https://i.postimg.cc/htfxrg4h/Samsung-Galaxy-A13.png",
    camera: "50MP",
    megapixels: 50,
    cameraCount: 4,
    description:
      "Бюджетный смартфон с большим экраном и продолжительным временем работы.",
  },
  {
    id: "google-pixel-7-pro",
    name: "Google Pixel 7 Pro",
    price: 75000,
    brand: "Pixel",
    memory: 256,
    image: "https://i.postimg.cc/VsDCQ221/Google-Pixel-7-Pro.png",
    camera: "50MP",
    megapixels: 50,
    cameraCount: 3,
    description:
      "Премиальный смартфон с выдающимися возможностями камеры и чистым Android.",
  },
  {
    id: "google-pixel-7a",
    name: "Google Pixel 7a",
    price: 45000,
    brand: "Pixel",
    memory: 128,
    image: "https://i.postimg.cc/xT8b0tSm/Google-Pixel-7a.png",
    camera: "64MP",
    megapixels: 64,
    cameraCount: 2,
    description:
      "Отличный смартфон с интеллектуальной камерой и быстрой работой.",
  },
  {
    id: "google-pixel-6a",
    name: "Google Pixel 6a",
    price: 38000,
    brand: "Pixel",
    memory: 128,
    image: "https://i.postimg.cc/QCxKKq9R/Google-Pixel-6a.png",
    camera: "12MP",
    megapixels: 12,
    cameraCount: 2,
    description:
      "Компактный и доступный Pixel с отличными фотографическими возможностями.",
  },
  {
    id: "google-pixel-fold",
    name: "Google Pixel Fold",
    price: 180000,
    brand: "Pixel",
    memory: 256,
    image: "https://i.postimg.cc/pLnhjrrX/Google-Pixel-Fold.png",
    camera: "48MP",
    megapixels: 48,
    cameraCount: 3,
    description:
      "Первый складной смартфон от Google с уникальным дизайном и чистым Android.",
  },

  {
    id: "apple-iphone-15-pro-max",
    name: "Apple iPhone 15 Pro Max",
    price: 159990,
    brand: "Apple",
    memory: 256,
    camera: "48MP",
    megapixels: 48,
    cameraCount: 3,
    image: "https://i.postimg.cc/B6C1vz6T/Apple-i-Phone-15-Pro-Max.png",
    description:
      "Продвинутый смартфон с профессиональной тройной камерой и высокой производительностью для любых задач.",
  },
  {
    id: "apple-iphone-15",
    name: "Apple iPhone 15",
    price: 109990,
    brand: "Apple",
    memory: 128,
    camera: "48MP",
    megapixels: 48,
    cameraCount: 2,
    image: "https://i.postimg.cc/T3ymcQ7x/Apple-i-Phone-15.png",
    description:
      "Современный смартфон с двойной камерой высокого разрешения и мощным процессором.",
  },
  {
    id: "samsung-galaxy-s24-ultra",
    name: "Samsung Galaxy S24 Ultra",
    price: 139990,
    brand: "Samsung",
    memory: 512,
    camera: "200MP",
    megapixels: 200,
    cameraCount: 4,
    image: "https://i.postimg.cc/GmYt2fg4/Samsung-Galaxy-S24-Ultra.png",
    description:
      "Флагманский смартфон с мощной квадро-камерой, обеспечивающей высокое качество снимков, и быстрой производительностью.",
  },
  {
    id: "samsung-galaxy-a34",
    name: "Samsung Galaxy A34",
    price: 29990,
    brand: "Samsung",
    memory: 128,
    camera: "48MP",
    megapixels: 48,
    cameraCount: 3,
    image: "https://i.postimg.cc/mZXt6CFg/Samsung-Galaxy-A34.png",
    description:
      "Надежный смартфон с тройной камерой и большим запасом памяти для повседневного использования.",
  },
  {
    id: "google-pixel-8-pro",
    name: "Google Pixel 8 Pro",
    price: 99990,
    brand: "Pixel",
    memory: 256,
    camera: "50MP",
    megapixels: 50,
    cameraCount: 3,
    image: "https://i.postimg.cc/KYSKDb37/Google-Pixel-8-Pro.png",
    description:
      "Смартфон премиум-класса с тройной камерой и интеллектуальными функциями от Google.",
  },
  {
    id: "google-pixel-8",
    name: "Google Pixel 8",
    price: 79990,
    brand: "Pixel",
    memory: 128,
    camera: "50MP",
    megapixels: 50,
    cameraCount: 2,
    image: "https://i.postimg.cc/m2n1hCb5/Google-Pixel-8.png",
    description:
      "Компактный и мощный смартфон с двойной камерой и быстрой операционной системой.",
  },
  {
    id: "infinix-hot-30",
    name: "Infinix Hot 30",
    price: 12990,
    brand: "Infinix",
    memory: 128,
    camera: "50MP",
    megapixels: 50,
    cameraCount: 2,
    image: "https://i.postimg.cc/C1Jz0fPJ/Infinix-Hot-30.png",
    description:
      "Доступный смартфон с двойной камерой и большим экраном для развлечений.",
  },
  {
    id: "infinix-note-30",
    name: "Infinix Note 30",
    price: 18990,
    brand: "Infinix",
    memory: 256,
    camera: "64MP",
    megapixels: 64,
    cameraCount: 3,
    image: "https://i.postimg.cc/6q3Tp5FK/Infinix-Note-30.png",
    description:
      "Бюджетный смартфон с тройной камерой и высокой автономностью.",
  },
  {
    id: "honor-magic5-pro",
    name: "Honor Magic5 Pro",
    price: 89990,
    brand: "Honor",
    memory: 512,
    camera: "50MP",
    megapixels: 50,
    cameraCount: 3,
    image: "https://i.postimg.cc/qRpzWGLz/Honor-Magic5-Pro.png",
    description:
      "Мощный смартфон с инновационной тройной камерой и уникальным дизайном.",
  },
  {
    id: "honor-90",
    name: "Honor 90",
    price: 49990,
    brand: "Honor",
    memory: 256,
    camera: "200MP",
    megapixels: 200,
    cameraCount: 3,
    image: "https://i.postimg.cc/9fdDxky6/Honor-90.png",
    description:
      "Элегантный смартфон с камерой сверхвысокого разрешения и большим объемом памяти.",
  },
  {
    id: "xiaomi-13-ultra",
    name: "Xiaomi 13 Ultra",
    price: 109990,
    brand: "Xiaomi",
    memory: 512,
    camera: "50MP",
    megapixels: 50,
    cameraCount: 4,
    image: "https://i.postimg.cc/0N0NGwsx/Xiaomi-13-Ultra.png",
    description:
      "Премиальный смартфон с профессиональной квадро-камерой и топовыми характеристиками.",
  },
  {
    id: "xiaomi-redmi-note-12",
    name: "Xiaomi Redmi Note 12",
    price: 16990,
    brand: "Xiaomi",
    memory: 128,
    camera: "50MP",
    megapixels: 50,
    cameraCount: 3,
    image: "https://i.postimg.cc/mDZgmgL9/Xiaomi-Redmi-Note-12.png",
    description:
      "Бюджетный смартфон с тройной камерой и быстрым процессором для повседневных задач.",
  },

  {
    id: "samsung-galaxy-tab-s9-fe",
    name: "Samsung Galaxy Tab S9 FE",
    price: 35000,
    brand: "Samsung",
    memory: 128,
    image: "https://i.postimg.cc/HsLmBQns/samsung-galaxy-tab-s9-fe.png",
    camera: "8MP",
    megapixels: 8,
    cameraCount: 1,
    description:
      "Яркий и производительный планшет для работы и развлечений с отличным экраном и долгой автономностью.",
  },
  {
    id: "apple-ipad-air-5",
    name: "Apple iPad Air 5",
    price: 65000,
    brand: "Apple",
    memory: 256,
    image: "https://i.postimg.cc/tJxMMCKk/apple-ipad-air-5.png",
    camera: "12MP",
    megapixels: 12,
    cameraCount: 1,
    description:
      "Мощный и легкий планшет с чипом M1, идеальный для творчества и требовательных задач.",
  },
  {
    id: "xiaomi-pad-6",
    name: "Xiaomi Pad 6",
    price: 28000,
    brand: "Xiaomi",
    memory: 128,
    image: "https://i.postimg.cc/1XwvK7FY/xiaomi-pad-6.png",
    camera: "13MP",
    megapixels: 13,
    cameraCount: 1,
    description:
      "Универсальный планшет с высокой частотой обновления экрана и отличным соотношением цена/качество.",
  },
  {
    id: "huawei-matepad-pro-11",
    name: "Huawei MatePad Pro 11",
    price: 42000,
    brand: "Huawei",
    memory: 256,
    image: "https://i.postimg.cc/c1pj8w3b/huawei-matepad-pro-11.png",
    camera: "13MP",
    megapixels: 13,
    cameraCount: 1,
    description:
      "Элегантный планшет с OLED-экраном и мощным процессором, идеально подходящий для продуктивности.",
  },
  {
    id: "lenovo-tab-p11-pro-gen2",
    name: "Lenovo Tab P11 Pro Gen 2",
    price: 38000,
    brand: "Lenovo",
    memory: 128,
    image: "#", // Изображение не было предоставлено в HTML, оставляю заглушку
    camera: "8MP",
    megapixels: 8,
    cameraCount: 1,
    description:
      "Премиальный планшет с ярким OLED-дисплеем и длительным временем работы от батареи.",
  },
  {
    id: "samsung-galaxy-tab-a8",
    name: "Samsung Galaxy Tab A8",
    price: 18000,
    brand: "Samsung",
    memory: 64,
    image: "https://i.postimg.cc/rmdnDwwT/samsung-galaxy-tab-a8.png",
    camera: "8MP",
    megapixels: 8,
    cameraCount: 1,
    description:
      "Доступный планшет для повседневных задач, просмотра контента и онлайн-обучения.",
  },
  {
    id: "apple-ipad-10th-gen",
    name: "Apple iPad 10th Gen",
    price: 55000,
    brand: "Apple",
    memory: 64,
    image: "https://i.postimg.cc/ZYwnbYyn/apple-ipad-10th.png",
    camera: "12MP",
    megapixels: 12,
    cameraCount: 1,
    description:
      "Обновленный базовый iPad с новым дизайном и мощным процессором A14 Bionic.",
  },
  {
    id: "xiaomi-redmi-pad-se",
    name: "Xiaomi Redmi Pad SE",
    price: 15000,
    brand: "Xiaomi",
    memory: 128,
    image: "https://i.postimg.cc/fL6HmQV9/xiaomi-redmi-pad-se.png",
    camera: "8MP",
    megapixels: 8,
    cameraCount: 1,
    description:
      "Бюджетный планшет с большим экраном и хорошей автономностью для всей семьи.",
  },
  {
    id: "honor-pad-x9",
    name: "Honor Pad X9",
    price: 22000,
    brand: "Honor",
    memory: 128,
    image: "https://i.postimg.cc/J7DvnPsX/Honor-Pad-X9.png",
    camera: "5MP",
    megapixels: 5,
    cameraCount: 1,
    description:
      "Стильный и легкий планшет с качественным дисплеем, идеально подходящий для просмотра медиа.",
  },
  {
    id: "realme-pad-2",
    name: "Realme Pad 2",
    price: 20000,
    brand: "Realme",
    memory: 64,
    image: "https://i.postimg.cc/3xBb6qcs/realme-pad-2.png",
    camera: "8MP",
    megapixels: 8,
    cameraCount: 1,
    description:
      "Тонкий и мощный планшет с большим экраном и быстрой зарядкой.",
  },
  {
    id: "oneplus-pad",
    name: "OnePlus Pad",
    price: 50000,
    brand: "OnePlus",
    memory: 256,
    image: "https://i.postimg.cc/xd1FSRrc/oneplus-pad.png",
    camera: "13MP",
    megapixels: 13,
    cameraCount: 1,
    description:
      "Флагманский планшет с уникальным соотношением сторон экрана и быстрой производительностью.",
  },
  {
    id: "google-pixel-tablet",
    name: "Google Pixel Tablet",
    price: 45000,
    brand: "Pixel",
    memory: 128,
    image: "https://i.postimg.cc/9FykP0tF/Google-Pixel-Tablet.png",
    camera: "8MP",
    megapixels: 8,
    cameraCount: 1,
    description:
      "Первый планшет от Google с док-станцией для умного дома и чистым Android.",
  },
  {
    id: "apple-ipad-pro-12-9-m2",
    name: "Apple iPad Pro 12.9 (M2)",
    price: 120000,
    brand: "Apple",
    memory: 256,
    image: "https://i.postimg.cc/FKT8f6by/Apple-i-Pad-Pro-12-9-M2.png",
    camera: "12MP",
    megapixels: 12,
    cameraCount: 2,
    description:
      "Профессиональный планшет с чипом M2, Liquid Retina XDR дисплеем и продвинутыми камерами.",
  },
  {
    id: "apple-ipad-air-4",
    name: "Apple iPad Air 4",
    price: 50000,
    brand: "Apple",
    memory: 64,
    image: "https://i.postimg.cc/B6yzp1Vt/apple-ipad-air-4.png",
    camera: "12MP",
    megapixels: 12,
    cameraCount: 1,
    description:
      "Мощный и универсальный планшет с поддержкой Apple Pencil 2 и Magic Keyboard.",
  },
  {
    id: "apple-ipad-mini-6",
    name: "Apple iPad mini 6",
    price: 58000,
    brand: "Apple",
    memory: 64,
    image: "https://i.postimg.cc/VNf2kwts/Apple-i-Pad-mini-6.png",
    camera: "12MP",
    megapixels: 12,
    cameraCount: 1,
    description:
      "Компактный и мощный планшет с новым дизайном и процессором A15 Bionic.",
  },
  {
    id: "apple-ipad-9th-gen",
    name: "Apple iPad 9th Gen",
    price: 40000,
    brand: "Apple",
    memory: 64,
    image: "https://i.postimg.cc/htbHnvf3/apple-ipad-9th.png",
    camera: "8MP",
    megapixels: 8,
    cameraCount: 1,
    description:
      "Надежный и доступный iPad для повседневных задач, учебы и развлечений.",
  },
  {
    id: "apple-ipad-pro-11-m4",
    name: "Apple iPad Pro 11 (M4)",
    price: 105000,
    brand: "Apple",
    memory: 256,
    image: "https://i.postimg.cc/mgG0KC2H/Apple-i-Pad-Pro-11-M4.png",
    camera: "12MP",
    megapixels: 12,
    cameraCount: 2,
    description:
      "Ультратонкий и мощный планшет с чипом M4, идеальный для профессионалов и творческих задач.",
  },

  {
    id: "samsung-neo-qled-qn90c",
    name: "Samsung Neo QLED QN90C",
    price: 150000,
    brand: "Samsung",
    screenSize: 55, // в дюймах
    resolution: "4K UHD",
    technology: "QLED",
    smartTv: true,
    refreshRate: 120, // в Гц
    image: "https://i.postimg.cc/tT9pk29g/Samsung-The-Serif-LS01-B.jpg",
    description:
      "Флагманский 4K QLED-телевизор с невероятной яркостью и точной цветопередачей.",
  },
  {
    id: "lg-oled-c3",
    name: "LG OLED C3",
    price: 180000,
    brand: "LG",
    screenSize: 65,
    resolution: "4K UHD",
    technology: "OLED",
    smartTv: true,
    refreshRate: 120,
    image: "https://i.postimg.cc/cLVJRRKK/LG-OLED-C3.png",
    description:
      "Идеальный выбор для киноманов и геймеров благодаря глубокому черному цвету и мгновенному отклику.",
  },
  {
    id: "sony-bravia-x85l",
    name: "Sony Bravia X85L",
    price: 95000,
    brand: "Sony",
    screenSize: 50,
    resolution: "4K UHD",
    technology: "LED",
    smartTv: true,
    refreshRate: 120,
    image: "https://i.postimg.cc/Y2nMN6Zp/Sony-Bravia-X85-L.jpg",
    description:
      "Высококачественный телевизор с процессором Sony X1 для улучшенной детализации и цветопередачи.",
  },
  {
    id: "hisense-u8k",
    name: "Hisense U8K",
    price: 110000,
    brand: "Hisense",
    screenSize: 55,
    resolution: "4K UHD",
    technology: "Mini-LED",
    smartTv: true,
    refreshRate: 144,
    image: "https://i.postimg.cc/j2Z5PBNK/Hisense-U8-K.png",
    description:
      "Мощный Mini-LED телевизор с высокой яркостью и поддержкой всех современных стандартов HDR.",
  },
  {
    id: "samsung-the-frame-ls03b",
    name: "Samsung The Frame LS03B",
    price: 85000,
    brand: "Samsung",
    screenSize: 50,
    resolution: "4K UHD",
    technology: "QLED",
    smartTv: true,
    refreshRate: 60,
    image: "https://i.postimg.cc/xdv9LWD7/Samsung-The-Frame-LS03-B.jpg",
    description:
      "Телевизор-картина, который превращается в произведение искусства, когда вы его не используете.",
  },
  {
    id: "lg-full-hd-24tl510s-pz",
    name: "LG Full HD 24TL510S-PZ",
    price: 15000,
    brand: "LG",
    screenSize: 24,
    resolution: "Full HD",
    technology: "LED",
    smartTv: true,
    refreshRate: 60,
    image: "https://i.postimg.cc/2jw3sLtJ/LG-Full-HD-24-TL510-S-PZ.jpg",
    description:
      "Компактный Smart-телевизор для кухни или небольшой спальни с отличным качеством изображения.",
  },
  // НОВАЯ ЗАПИСЬ: Philips The One PUS8808
  {
    id: "philips-the-one-pus8808",
    name: "Philips The One PUS8808",
    price: 75000,
    brand: "Philips",
    screenSize: 55,
    resolution: "4K UHD",
    technology: "LED",
    smartTv: true,
    refreshRate: 120,
    image: "https://i.postimg.cc/fyTWz5PP/Philips-The-One-PUS8808.jpg",
    description:
      "Универсальный 4K-телевизор Philips с технологией Ambilight, обеспечивающий захватывающий просмотр.",
  },

  {
    id: "samsung-qn85c",
    name: "Samsung QN85C",
    price: 130000,
    brand: "Samsung",
    screenSize: 55,
    resolution: "4K UHD",
    technology: "Neo QLED",
    smartTv: true,
    refreshRate: 120,
    image: "https://i.postimg.cc/zXvD4tKb/Samsung-QN85-C.jpg", // Замените на реальное изображение
    description:
      "Премиальный Neo QLED телевизор с отличной яркостью и контрастом для ярких впечатлений от просмотра.",
  },
  {
    id: "lg-qned80",
    name: "LG QNED80",
    price: 90000,
    brand: "LG",
    screenSize: 65,
    resolution: "4K UHD",
    technology: "QNED",
    smartTv: true,
    refreshRate: 120,
    image: "https://i.postimg.cc/pTvX7PJR/LG-QNED80.jpg", // Замените на реальное изображение
    description:
      "Телевизор LG QNED с технологией Quantum Dot и NanoCell для точной цветопередачи и яркого изображения.",
  },
  {
    id: "sony-bravia-x90k",
    name: "Sony Bravia X90K",
    price: 115000,
    brand: "Sony",
    screenSize: 55,
    resolution: "4K UHD",
    technology: "Full Array LED",
    smartTv: true,
    refreshRate: 120,
    image: "https://i.postimg.cc/BQjsm8f2/Sony-Bravia-X90-K.jpg", // Замените на реальное изображение
    description:
      "Телевизор с Full Array LED подсветкой и процессором Cognitive Processor XR для реалистичного изображения.",
  },
  {
    id: "hisense-u7k",
    name: "Hisense U7K",
    price: 80000,
    brand: "Hisense",
    screenSize: 50,
    resolution: "4K UHD",
    technology: "Mini-LED",
    smartTv: true,
    refreshRate: 120,
    image: "https://i.postimg.cc/TPDpF78q/Hisense-U7-K.png", // Замените на реальное изображение
    description:
      "Доступный Mini-LED телевизор с высокой яркостью и отличной производительностью для игр.",
  },
  {
    id: "tcl-q7",
    name: "TCL Q7",
    price: 65000,
    brand: "TCL",
    screenSize: 55,
    resolution: "4K UHD",
    technology: "QLED",
    smartTv: true,
    refreshRate: 120,
    image: "https://i.postimg.cc/htxnqHjj/TCL-Q7.jpg", // Замените на реальное изображение
    description:
      "QLED телевизор с хорошим качеством изображения и поддержкой Google TV для удобного доступа к контенту.",
  },
  {
    id: "xiaomi-tv-a2-43",
    name: "Xiaomi TV A2 43",
    price: 35000,
    brand: "Xiaomi",
    screenSize: 43,
    resolution: "4K UHD",
    technology: "LED",
    smartTv: true,
    refreshRate: 60,
    image: "https://i.postimg.cc/bJYfkrRD/Xiaomi-TV-A2-43.jpg", // Замените на реальное изображение
    description:
      "Бюджетный 4K Smart TV с Android TV, предлагающий базовый набор функций для повседневного просмотра.",
  },
  {
    id: "philips-oled808",
    name: "Philips OLED808",
    price: 190000,
    brand: "Philips",
    screenSize: 65,
    resolution: "4K UHD",
    technology: "OLED",
    smartTv: true,
    refreshRate: 120,
    image: "https://i.postimg.cc/V6FLP2KM/Philips-OLED808.jpg", // Замените на реальное изображение
    description:
      "Флагманский OLED телевизор Philips с технологией Ambilight, обеспечивающий потрясающее изображение и атмосферу.",
  },

  {
    id: "samsung-qn90a",
    name: "Samsung QN90A",
    price: 140000,
    brand: "Samsung",
    screenSize: 65,
    resolution: "4K UHD",
    technology: "Neo QLED",
    smartTv: true,
    refreshRate: 120,
    image: "https://i.postimg.cc/zXQDNCFd/Samsung-QN90-A.jpg",
    description:
      "Превосходный Neo QLED телевизор с мини-LED подсветкой, обеспечивающий невероятную яркость и контраст.",
  },
  {
    id: "lg-oled-g2",
    name: "LG OLED G2",
    price: 200000,
    brand: "LG",
    screenSize: 77,
    resolution: "4K UHD",
    technology: "OLED evo",
    smartTv: true,
    refreshRate: 120,
    image: "https://i.postimg.cc/hGTtpXx2/LG-OLED-G2.jpg",
    description:
      "Флагманский OLED evo телевизор с улучшенной яркостью и дизайном Gallery Design для крепления вплотную к стене.",
  },
  {
    id: "sony-bravia-a80j",
    name: "Sony Bravia A80J",
    price: 160000,
    brand: "Sony",
    screenSize: 65,
    resolution: "4K UHD",
    technology: "OLED",
    smartTv: true,
    refreshRate: 120,
    image: "https://i.postimg.cc/Z5yb5WfJ/Sony-Bravia-A80-J.jpg",
    description:
      "OLED телевизор с процессором Cognitive Processor XR, обеспечивающий реалистичное изображение и звук.",
  },
  {
    id: "hisense-u6g",
    name: "Hisense U6G",
    price: 60000,
    brand: "Hisense",
    screenSize: 55,
    resolution: "4K UHD",
    technology: "ULED",
    smartTv: true,
    refreshRate: 60,
    image: "https://i.postimg.cc/Y9BhH6Mc/Hisense-U6-G.jpg",
    description:
      "Доступный ULED телевизор с технологией Quantum Dot для ярких и точных цветов.",
  },
  {
    id: "tcl-c725",
    name: "TCL C725",
    price: 50000,
    brand: "TCL",
    screenSize: 50,
    resolution: "4K UHD",
    technology: "QLED",
    smartTv: true,
    refreshRate: 60,
    image: "https://i.postimg.cc/X7tWmVnm/TCL-C725.png",
    description:
      "QLED телевизор с Android TV и поддержкой Google Assistant для умного дома.",
  },
  {
    id: "xiaomi-tv-q1e-75",
    name: "Xiaomi TV Q1E 75",
    price: 120000,
    brand: "Xiaomi",
    screenSize: 75,
    resolution: "4K UHD",
    technology: "QLED",
    smartTv: true,
    refreshRate: 120,
    image: "https://i.postimg.cc/bJ6cTP66/Xiaomi-TV-Q1-E-75.jpg",
    description:
      "Большой QLED телевизор Xiaomi с высоким качеством изображения и широким функционалом Smart TV.",
  },
  {
    id: "philips-pus7906",
    name: "Philips PUS7906",
    price: 45000,
    brand: "Philips",
    screenSize: 43,
    resolution: "4K UHD",
    technology: "LED",
    smartTv: true,
    refreshRate: 60,
    image: "https://i.postimg.cc/T17dpgM3/Philips-PUS7906.png",
    description:
      "Доступный 4K Smart TV Philips с технологией Ambilight для более захватывающего просмотра.",
  },
  {
    id: "lg-oled-a2",
    name: "LG OLED A2",
    price: 100000,
    brand: "LG",
    screenSize: 48,
    resolution: "4K UHD",
    technology: "OLED",
    smartTv: true,
    refreshRate: 60,
    image: "https://i.postimg.cc/fTqyLnDf/LG-OLED-A2.jpg",
    description:
      "Базовый OLED телевизор LG с прекрасным качеством изображения и идеальным черным цветом.",
  },
  {
    id: "sony-bravia-x75k",
    name: "Sony Bravia X75K",
    price: 70000,
    brand: "Sony",
    screenSize: 55,
    resolution: "4K UHD",
    technology: "LED",
    smartTv: true,
    refreshRate: 60,
    image: "https://i.postimg.cc/SsVqvCKf/Sony-Bravia-X75-K.jpg",
    description:
      "Надежный 4K Smart TV Sony с ярким изображением и простым доступом к любимым развлечениям.",
  },
  {
    id: "hisense-a6h",
    name: "Hisense A6H",
    price: 30000,
    brand: "Hisense",
    screenSize: 43,
    resolution: "4K UHD",
    technology: "LED",
    smartTv: true,
    refreshRate: 60,
    image: "https://i.postimg.cc/KjZjKm1J/Hisense-A6-H.png",
    description:
      "Бюджетный 4K Smart TV Hisense с Vidaa U Smart TV OS для быстрого и удобного доступа к контенту.",
  },

  // Телевизоры с размером экрана 33-49 дюймов
  {
    id: "sony-bravia-kd43x85k",
    name: "Sony Bravia KD43X85K",
    price: 65000,
    brand: "Sony",
    screenSize: 43,
    resolution: "4K UHD",
    technology: "LED",
    smartTv: true,
    refreshRate: 120,
    image: "https://i.postimg.cc/NFMYqF9q/Sony-Bravia-KD43-X85-K.jpg",
    description:
      "43-дюймовый 4K-телевизор с технологией Motionflow XR для плавного изображения и яркой цветопередачей.",
  },
  {
    id: "samsung-the-serif-ls01b",
    name: "Samsung The Serif LS01B",
    price: 95000,
    brand: "Samsung",
    screenSize: 43,
    resolution: "4K UHD",
    technology: "QLED",
    smartTv: true,
    refreshRate: 60,
    image: "https://i.postimg.cc/tT9pk29g/Samsung-The-Serif-LS01-B.jpg",
    description:
      "Стильный QLED-телевизор в уникальном дизайнерском корпусе, который прекрасно вписывается в современный интерьер.",
  },
  {
    id: "lg-oled-a2-48",
    name: "LG OLED A2 48",
    price: 110000,
    brand: "LG",
    screenSize: 48,
    resolution: "4K UHD",
    technology: "OLED",
    smartTv: true,
    refreshRate: 60,
    image: "https://i.postimg.cc/9FQzCF5f/LG-OLED-A2-48.jpg",
    description:
      "OLED-телевизор с идеальным черным цветом, идеально подходящий для небольших комнат или как дополнительный монитор.",
  },
  {
    id: "tcl-p635-43",
    name: "TCL P635 43",
    price: 32000,
    brand: "TCL",
    screenSize: 43,
    resolution: "4K UHD",
    technology: "LED",
    smartTv: true,
    refreshRate: 60,
    image: "https://i.postimg.cc/R0LzWKwx/TCL-P635-43.jpg",
    description:
      "Бюджетный 4K Smart TV с Google TV, предлагающий доступ к множеству приложений и сервисов.",
  },

  // Телевизоры без Smart TV и по доступной цене
  {
    id: "samsung-t5300-32",
    name: "Samsung T5300 32",
    price: 22000,
    brand: "Samsung",
    screenSize: 32,
    resolution: "Full HD",
    technology: "LED",
    smartTv: false,
    refreshRate: 60,
    image: "https://i.postimg.cc/Dzk2J7DL/Samsung-T5300.png",
    description:
      "Компактный и простой в использовании телевизор с Full HD разрешением, без функций Smart TV.",
  },
  {
    id: "hisense-a4h-32",
    name: "Hisense A4H",
    price: 20000,
    brand: "Hisense",
    screenSize: 32,
    resolution: "HD Ready",
    technology: "LED",
    smartTv: false,
    refreshRate: 60,
    image: "https://i.postimg.cc/Bnt8cZMz/Hisense-A4-H.jpg",
    description:
      "Бюджетная модель для кухни или дачи с базовым набором функций и разрешением HD Ready.",
  },
  {
    id: "erisson-19",
    name: "Erisson 19",
    price: 12000,
    brand: "Erisson",
    screenSize: 19,
    resolution: "HD Ready",
    technology: "LED",
    smartTv: false,
    refreshRate: 60,
    image: "https://i.postimg.cc/Sx5nZ0Px/Erisson-19.jpg",
    description:
      "Сверхкомпактный телевизор, идеальный для маленьких помещений или для использования в качестве монитора.",
  },
  {
    id: "thomson-32",
    name: "Thomson 32",
    price: 25000,
    brand: "Thomson",
    screenSize: 32,
    resolution: "Full HD",
    technology: "LED",
    smartTv: false,
    refreshRate: 60,
    image: "https://i.postimg.cc/1zQQRJnK/Thomson-32.jpg",
    description:
      "Надежный телевизор с Full HD изображением, без лишних функций Smart TV.",
  },

  // Дополнительные модели для разнообразия
  {
    id: "lg-oled-c2-42",
    name: "LG OLED C2 42",
    price: 105000,
    brand: "LG",
    screenSize: 42,
    resolution: "4K UHD",
    technology: "OLED",
    smartTv: true,
    refreshRate: 120,
    image: "https://i.postimg.cc/W1D3qW4L/LG-OLED-C2-42.jpg",
    description:
      "Модель C2 в компактном 42-дюймовом корпусе, идеальна для игр и фильмов на небольших пространствах.",
  },
  {
    id: "sony-bravia-a90k-48",
    name: "Sony Bravia A90K 48",
    price: 135000,
    brand: "Sony",
    screenSize: 48,
    resolution: "4K UHD",
    technology: "OLED",
    smartTv: true,
    refreshRate: 120,
    image: "https://i.postimg.cc/zvcNJNKL/Sony-Bravia-A90-K-48.jpg",
    description:
      "OLED-телевизор премиум-класса с выдающимся качеством изображения и звука от Sony.",
  },
  {
    id: "hisense-a7g-50",
    name: "Hisense A7G 50",
    price: 55000,
    brand: "Hisense",
    screenSize: 50,
    resolution: "4K UHD",
    technology: "LED",
    smartTv: true,
    refreshRate: 60,
    image: "https://i.postimg.cc/G2P9h4m4/Hisense-A7-G-50.png",
    description:
      "Яркий и контрастный 4K-телевизор с технологией Quantum Dot от Hisense.",
  },

  {
    id: "lenovo-ideapad-5i",
    name: "Lenovo IdeaPad 5i",
    price: 65000,
    brand: "Lenovo",
    ram: "16",
    ssd: "512",
    screenSize: "15.6",
    processor: "Intel Core i5",
    image: "https://i.postimg.cc/Gm6c8Vq0/Lenovo-Idea-Pad-5i.png",
    description:
      "Стильный и мощный ноутбук для работы и учебы. Оснащен процессором Intel Core i5, 16 ГБ ОЗУ и 512 ГБ SSD.",
  },
  {
    id: "hp-pavilion-14",
    name: "HP Pavilion 14",
    price: 55000,
    brand: "HP",
    ram: "8",
    ssd: "256",
    screenSize: "14",
    processor: "Intel Core i5",
    image: "https://i.postimg.cc/XqxjrvDx/HP-Pavilion-14.png",
    description:
      "Компактный и легкий ноутбук HP Pavilion 14 идеально подходит для повседневных задач и мультимедиа.",
  },
  {
    id: "dell-xps-13",
    name: "Dell XPS 13",
    price: 120000,
    brand: "Dell",
    ram: "16",
    ssd: "512",
    screenSize: "13.4",
    processor: "Intel Core i7",
    image: "https://i.postimg.cc/jqhdg8dN/Dell-XPS-13.png",
    description:
      "Dell XPS 13 — это премиальный ультрабук с безупречным дизайном, мощным процессором и ярким экраном.",
  },
  {
    id: "apple-macbook-air-m2",
    name: "Apple MacBook Air M2",
    price: 150000,
    brand: "Apple",
    ram: "8",
    ssd: "256",
    screenSize: "13.6",
    processor: "M2",
    image: "https://i.postimg.cc/HspjdqPB/Apple-Mac-Book-Air-M2.png",
    description:
      "Невероятно тонкий и легкий MacBook Air с чипом Apple M2 обеспечивает выдающуюся производительность и долгую работу от батареи.",
  },
  {
    id: "acer-nitro-5",
    name: "Acer Nitro 5",
    price: 95000,
    brand: "Acer",
    ram: "16",
    ssd: "512",
    screenSize: "15.6",
    processor: "AMD Ryzen 5",
    image: "https://i.postimg.cc/ryGK6VgD/Acer-Nitro-5.png",
    description:
      "Игровой ноутбук Acer Nitro 5 предлагает высокую производительность и эффективное охлаждение для захватывающих игр.",
  },
  {
    id: "asus-vivobook-pro",
    name: "Asus VivoBook Pro",
    price: 89000,
    brand: "Asus",
    ram: "16",
    ssd: "1024",
    screenSize: "15.6",
    processor: "Intel Core i7",
    image: "https://i.postimg.cc/QdCtWpD7/Asus-Vivo-Book-Pro.png",
    description:
      "Asus VivoBook Pro — идеальное решение для создателей контента и профессионалов, ценящих высокую производительность и качество дисплея.",
  },
  {
    id: "huawei-matebook-d16",
    name: "Huawei MateBook D 16",
    price: 75000,
    brand: "Huawei",
    ram: "16",
    ssd: "512",
    screenSize: "16",
    processor: "Intel Core i5",
    image: "https://i.postimg.cc/x1XfdnGy/Huawei-Mate-Book-D-16.png",
    description:
      "Большой экран и высокая производительность делают Huawei MateBook D 16 отличным выбором для работы и развлечений.",
  },
  {
    id: "apple-macbook-pro-14",
    name: "Apple MacBook Pro 14",
    price: 250000,
    brand: "Apple",
    ram: "16",
    ssd: "1024",
    screenSize: "14.2",
    processor: "M2",
    image: "https://i.postimg.cc/G3x77Q6v/Dell-XPS.png",
    description:
      "Мощный MacBook Pro 14 с чипом M2 Pro создан для самых требовательных задач, таких как видеомонтаж и 3D-моделирование.",
  },
  {
    id: "lenovo-yoga-7",
    name: "Lenovo Yoga 7",
    price: 85000,
    brand: "Lenovo",
    ram: "16",
    ssd: "512",
    screenSize: "14",
    processor: "Intel Core i7",
    image: "https://i.postimg.cc/Hx9HNxHH/Lenovo-Yoga-7.png",
    description:
      "Lenovo Yoga 7 — универсальный ноутбук-трансформер с сенсорным экраном, который легко адаптируется под любые задачи.",
  },
  {
    id: "hp-envy-x360",
    name: "HP Envy x360",
    price: 99000,
    brand: "HP",
    ram: "16",
    ssd: "1024",
    screenSize: "15.6",
    processor: "AMD Ryzen 5",
    image: "https://i.postimg.cc/kG7MMSwB/HP-Envy-x360.png",
    description:
      "HP Envy x360 — это стильный ноутбук-трансформер с мощным процессором, который подходит как для творчества, так и для развлечений.",
  },
  {
    id: "dell-inspiron-15",
    name: "Dell Inspiron 15",
    price: 48000,
    brand: "Dell",
    ram: "8",
    ssd: "512",
    screenSize: "15.6",
    processor: "Intel Core i5",
    image: "https://i.postimg.cc/NM6fwD63/Dell-Inspiron-15.png",
    description:
      "Dell Inspiron 15 — надежный и доступный ноутбук для учебы и работы, с большим экраном и вместительным хранилищем.",
  },
  {
    id: "asus-zenbook",
    name: "Asus ZenBook",
    price: 135000,
    brand: "Asus",
    ram: "16",
    ssd: "1024",
    screenSize: "13.3",
    processor: "Intel Core i7",
    image: "https://i.postimg.cc/mrFgmBt2/Asus-Zen-Book.png",
    description:
      "Asus ZenBook — это ультратонкий и элегантный ноутбук с высокой производительностью и длительным временем автономной работы.",
  },
  {
    id: "samsung-galaxy-book3",
    name: "Samsung Galaxy Book3",
    price: 110000,
    brand: "Samsung",
    ram: "16",
    ssd: "512",
    screenSize: "15.6",
    processor: "Intel Core i7",
    image: "https://i.postimg.cc/ZKRZf4Qt/Samsung-Galaxy-Book3.png",
    description:
      "Samsung Galaxy Book3 — легкий и тонкий ноутбук с ярким экраном, который обеспечивает высокую производительность для повседневных задач.",
  },
  {
    id: "microsoft-surface-laptop-5",
    name: "Microsoft Surface Laptop 5",
    price: 145000,
    brand: "Microsoft",
    ram: "16",
    ssd: "512",
    screenSize: "13.5",
    processor: "Intel Core i7",
    image: "https://i.postimg.cc/sfKs9vw4/Microsoft-Surface-Laptop-5.png",
    description:
      "Microsoft Surface Laptop 5 — стильный и мощный ноутбук с сенсорным экраном, созданный для комфортной работы и творчества.",
  },
  {
    id: "lg-gram-17",
    name: "LG Gram 17",
    price: 130000,
    brand: "LG",
    ram: "16",
    ssd: "1024",
    screenSize: "17",
    processor: "Intel Core i7",
    image: "https://i.postimg.cc/0jtv8BbB/LG-Gram-17.png",
    description:
      "LG Gram 17 — это невероятно легкий 17-дюймовый ноутбук, сочетающий в себе большой экран и высокую портативность.",
  },
  {
    id: "asus-rog-zephyrus-g14",
    name: "Asus ROG Zephyrus G14",
    price: 180000,
    brand: "Asus",
    ram: "32",
    ssd: "1024",
    screenSize: "14",
    processor: "AMD Ryzen 9",
    image: "https://i.postimg.cc/BbC62ptT/Asus-ROG-Zephyrus-G14.png",
    description:
      "Asus ROG Zephyrus G14 — мощный игровой ноутбук в компактном корпусе, идеальный для геймеров, которые всегда в движении.",
  },
  {
    id: "hp-spectre-x360",
    name: "HP Spectre x360",
    price: 140000,
    brand: "HP",
    ram: "16",
    ssd: "1024",
    screenSize: "13.5",
    processor: "Intel Core i7",
    image: "https://i.postimg.cc/Ghh3ZkHf/HP-Spectre-x360.png",
    description:
      "HP Spectre x360 — элегантный ноутбук-трансформер с экраном высокого разрешения, созданный для максимального удобства и стиля.",
  },
  {
    id: "lenovo-thinkpad-x1",
    name: "Lenovo ThinkPad X1 Carbon",
    price: 160000,
    brand: "Lenovo",
    ram: "32",
    ssd: "1024",
    screenSize: "14",
    processor: "Intel Core i7",
    image: "https://i.postimg.cc/mDsBV9v8/Lenovo-Think-Pad-X1-Carbon-1.png",
    description:
      "Lenovo ThinkPad X1 Carbon — ультралегкий и прочный бизнес-ноутбук с выдающейся производительностью и долгим временем работы.",
  },

  {
    id: "acer-swift-3",
    name: "Acer Swift 3",
    price: 60000,
    brand: "Acer",
    ram: "8",
    ssd: "512",
    screenSize: "14",
    processor: "AMD Ryzen 7",
    image: "https://i.postimg.cc/Rhmh3yCC/Acer-Swift-3.png",
    description:
      "Acer Swift 3 — это легкий и тонкий ноутбук, который обеспечивает отличный баланс между производительностью и портативностью.",
  },
  {
    id: "asus-zenbook-duo-14",
    name: "Asus ZenBook Duo 14",
    price: 175000,
    brand: "Asus",
    ram: "32",
    ssd: "1024",
    screenSize: "14",
    processor: "Intel Core i9",
    image: "https://i.postimg.cc/gJFk5QZy/Asus-Zen-Book-Duo-14.png",
    description:
      "Asus ZenBook Duo 14 с двумя экранами предлагает уникальные возможности для многозадачности и творчества.",
  },

  {
    id: "lg-gram-14",
    name: "LG Gram 14",
    price: 105000,
    brand: "LG",
    ram: "16",
    ssd: "512",
    screenSize: "14",
    processor: "Intel Core i5",
    image: "https://i.postimg.cc/D0fF3TyG/LG-Gram-14.png",
    description:
      "LG Gram 14 — это легкий и компактный ноутбук с долгим временем автономной работы, идеальный для тех, кто постоянно в пути.",
  },

  {
    id: "huawei-matebook-14s",
    name: "Huawei MateBook 14s",
    price: 115000,
    brand: "Huawei",
    ram: "16",
    ssd: "512",
    screenSize: "14.2",
    processor: "Intel Core i7",
    image: "https://i.postimg.cc/02W5xbSy/Huawei-Mate-Book-14s.png",
    description:
      "Huawei MateBook 14s — элегантный ноутбук с экраном FullView, высокой производительностью и долгим временем работы от батареи.",
  },

  {
    id: "lenovo-ideapad-gaming-3",
    name: "Lenovo IdeaPad Gaming 3",
    price: 90000,
    brand: "Lenovo",
    ram: "16",
    ssd: "512",
    screenSize: "15.6",
    processor: "AMD Ryzen 5",
    image: "https://i.postimg.cc/25vC4GK1/Lenovo-Idea-Pad-Gaming-3.png",
    description:
      "Lenovo IdeaPad Gaming 3 — отличный выбор для начинающих геймеров, предлагающий высокую производительность по доступной цене.",
  },
  {
    id: "asus-tuf-gaming-f15",
    name: "Asus TUF Gaming F15",
    price: 110000,
    brand: "Asus",
    ram: "16",
    ssd: "1024",
    screenSize: "15.6",
    processor: "Intel Core i7",
    image: "https://i.postimg.cc/8Ptc5Z2D/Asus-TUF-Gaming-F15.png",
    description:
      "Asus TUF Gaming F15 — надежный и прочный игровой ноутбук, созданный для долгой и интенсивной работы.",
  },
];
export { products };
